providers {
  ollama {
    baseUrl = "http://localhost:11434"
    requestTimeoutSeconds = 120
  }

  openai {
    baseUrl = "https://api.openai.com/v1"
    apiKey = ${?OPENAI_API_KEY}
  }
}

embeddings {
  active = "local-default"

  profiles {
    local-default {
      provider = "ollama"
      model = "embeddinggemma"
    }

    openai-default {
      provider = "openai"
      model = "text-embedding-3-small"
    }
  }
}

llms {
  active = "local-default"

  profiles {
    local-default {
      provider = "ollama"
      model = "gemma4:e4b"
    }

    openai-default {
      provider = "openai"
      model = "gpt-5.2"
    }
  }
}

neo4j {
  url = "neo4j://localhost:7687"
  username = ${?NEO4J_USERNAME}
  password = ${?NEO4J_PASSWORD}
  database = "essential-graph-rag"
}

chapter2 {
  pdfUrl = "https://arxiv.org/pdf/1709.00666.pdf"
  pdfPath = "data/ch02-downloadedpdf"

  chunkSize = 500
  chunkOverlap = 40
  topK = 4

  vectorIndex = "pdf"
  fulltextIndex = "ftPdfChunk"

  // If true, it will download the pdf and ingest into neo4j.
  ingest = true

  question = "At what time was Einstein really interested in experimental works?"
}